import "server-only";

/**
 * Provider-agnostic KYC verification contract. The rest of the application
 * (routes, the KYC state machine, the trader/admin UI data model) depends
 * only on this interface - never on a specific provider's request/response
 * shapes. Swapping identity-verification providers later means writing a
 * new class that implements this interface (see dojahKycProvider.ts for the
 * current one) and wiring it into kycVerification.ts; nothing else in the
 * KYC flow, and nothing outside it, needs to change.
 */

export type KycVerificationOutcome = "PENDING" | "VERIFIED" | "FAILED";

/**
 * The result of a provider verification, normalized to exactly what the
 * application needs and nothing provider-specific. Deliberately excludes
 * any identity data (names, ID numbers, document/selfie images) - those
 * never leave the provider's own systems as far as this application is
 * concerned.
 */
export type NormalizedKycResult = {
  outcome: KycVerificationOutcome;
  /** Safe, human-readable category - never the provider's raw response or any identity data. */
  failureReason?: string;
};

/**
 * Opaque, provider-specific data the trader-facing client needs to run a
 * verification session (e.g. Dojah's widget config). The KYC page component
 * is the only other place allowed to know this shape; the service layer and
 * everything below it treats it as opaque.
 */
export type KycSessionConfig = Record<string, unknown>;

export interface KycProvider {
  /** Short identifier stored on the KycSubmission row (e.g. "DOJAH"). */
  readonly name: string;

  /**
   * Prepares whatever the client needs to start a verification session with
   * this provider, addressed by our own `referenceId` (generated by the
   * caller, not the provider - see kycVerification.ts). Must not perform
   * any action that could itself grant verified status; providers whose
   * flow requires a server-initiated session may make that call here, but
   * must not be trusted to return a final result synchronously.
   */
  createVerificationSession(input: {
    referenceId: string;
    user: { id: string; name: string; email: string };
  }): Promise<KycSessionConfig>;

  /**
   * Authenticates an inbound provider webhook/callback request. Must be
   * checked before `parseWebhookPayload` is ever trusted.
   */
  verifyWebhookSignature(rawBody: string, headers: { get(name: string): string | null }): boolean;

  /**
   * Turns a provider webhook payload into our normalized result plus the
   * `referenceId` it corresponds to. Returns null if the payload can't be
   * parsed or doesn't carry a reference - callers must treat that as "no
   * action to take", never as a failure to report to the user.
   */
  parseWebhookPayload(rawBody: string): { referenceId: string; result: NormalizedKycResult } | null;
}
